In [1]:
# 1D
import numpy as np
var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])
ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 9 8 7 6]


In [6]:
# 2d concatenate along row(1) axis
import numpy as np
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])
ar_new = np.concatenate((vr,vr1),axis=1)  # row

print(vr,"\n")
print()
print(vr1)
print()
print(ar_new)

[[1 2]
 [3 4]] 


[[9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


In [12]:
# 2d concatenate along column(0) axis
import numpy as np
var3 = np.array([[1,2],[3,4]])
var4 = np.array([[9,8],[7,6]])
var5 = np.concatenate((var3,var4), axis=0)  # column
print()
print(var3)
print()
print(var4)
print()
print(var5)


[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [16]:
# STACK
import numpy as np
var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])
ar = np.stack((var,var1))
print(ar)

[[1 2 3 4]
 [9 8 7 6]]


In [18]:
import numpy as np
var = np.array(["a","b","c","d"])
var1 = np.array(["a","b","c","d"])
ar = np.stack((var,var1))
print(ar)

[['a' 'b' 'c' 'd']
 ['a' 'b' 'c' 'd']]


In [27]:
import numpy as np
var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

a_new = np.stack((var_1,var_2),axis=1) # here axis 1 means height
a_new1 = np.hstack((var_1,var_2))   # row
a_new2 = np.vstack((var_1,var_2))   # column
a_new3 = np.dstack((var_1,var_2))   # height

print(a_new)
print()
print(a_new1)
print()
print(a_new2)
print()
print(a_new3)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [3]:
import numpy as np
var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

a_new = np.stack((var_1,var_2),axis=0) column
print(a_new)

[[1 2 3 4]
 [9 8 7 6]]


hello world
