# creating arrays in numpy

In [1]:
pip install numpy

In [3]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
import numpy as np
x = [1,2,3,4]
y = np.array(x)
y

array([1, 2, 3, 4])

In [6]:
print(type(y))

<class 'numpy.ndarray'>


# Creating array by user input

In [11]:
l = []
for i in range(1,5):
    inp = int(input("enter the values: "))
    l.append(inp)

print(np.array(l))

enter the values:  1
enter the values:  2
enter the values:  3
enter the values:  4


[1 2 3 4]


In [12]:
print(type(l))

<class 'list'>


# Dimensions in Array


In [13]:
# 1-D Array
# 2-d
# 3-d
# Higher Dimensional arrays

In [14]:
# 1d array
y = np.array([1,2,3,4])
print(y)

[1 2 3 4]


# ndim

In [15]:
y.ndim

1

In [16]:
# 2d
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr2.ndim

2

In [18]:
# 3d
ar3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
ar3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [19]:
ar3.ndim

3

In [23]:
#  Multi dimensional array
arr = np.array([1,2,3,4], ndmin = 10)
arr

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

In [25]:
arr.ndim

10

# # create Numpy Arrays
# with Random Numbers

In [27]:
# 1. rand() - o to 1
# 2. randn() -> close to 0. may return +ve or -ve numbers as well
# 3. ranf() -> [0.0, 1.0)
# 4. randint() -> it generate a no. b/t a given range.

In [28]:
# code

In [29]:
# Random
# rand()
import numpy as np
var = np.random.rand(4)
var

array([0.69960531, 0.58696478, 0.32937227, 0.47942612])

In [30]:
# for 2d array
var1 = np.random.rand(2,5)    # row,column
var1

array([[0.36029095, 0.81993123, 0.91916316, 0.41648221, 0.8325181 ],
       [0.30260206, 0.6268136 , 0.12554286, 0.25755433, 0.06704044]])

In [31]:
# randn()
var2 = np.random.randn(5)
print(var2)

[ 1.2951494  -1.13901229 -1.85651147  0.49594255 -0.21800057]


In [35]:
# randf
var3 = np.random.ranf(4)
var3

array([0.84249756, 0.64091201, 0.37413763, 0.30272667])

In [38]:
# 4 randint()
# var4 = np.random.randint(min, max, total_values)
var4 = np.random.randint(5, 20, 5)
var4

array([ 9, 17, 13,  9, 19])

In [39]:
var4 = np.random.randint(5, 20, (2,5))
var4

array([[19, 13,  9,  8,  7],
       [15, 14, 13, 13,  5]])

In [40]:
var4.ndim

2

# Special Numpy Array


In [41]:
# 1. Array filled with 0's
# 2. Array filled with 1's
# 3. Create an empty
# 4. An array with the range of elements
# 5. Array diagonal element filled with 1's
# 6. Create an array with values that are spaced linearly in a specified interval

# ZEROS

In [48]:
import numpy as np
ar_zero = np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [49]:
# 2d 
import numpy as np
ar_zero = np.zeros((2,4)) # row, column
ar_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
# Ones
ar_one =np.ones(4)
ar_one

array([1., 1., 1., 1.])

In [55]:
# Empty
ar_emp = np.empty(4)
print(ar_emp)

[1. 1. 1. 1.]


In [58]:
# range
ar_rn = np.arange(4)
ar_rn
# output: array([0, 1, 2, 3])
# output is in continuous order

array([0, 1, 2, 3])

In [59]:
# diagonal
ar_dia = np.eye(3)
ar_dia

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
# linspace function
ar_lin = np.linspace(1,10,num=5)
ar_lin

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Data types in Numpy Arrays

In [62]:
# Difference between python data type and numpy datatype

In [64]:
# bool_
# int_
# Intc
# Intp
# Int8 and more...

In [65]:
# Data Type
import numpy as np
var = np.array([1,2,3,4])
print("Data Type: ", var.dtype) 

Data Type:  int32


# Data type can be change.



In [80]:
# Normal Code
x = np.array([1,2,3,4])
print("Data Type:", x.dtype)

Data Type: int32


In [71]:
# new array
x = np.array([1,2,3,4], dtype = np.int8)
print("Data Type : ", x.dtype)


Data Type :  int8


In [75]:
# Conversion of 1 Data Type to other
x= np.array([10,20,30,40])
print("Data Type: ", x.dtype)

Data Type:  int32


In [79]:
# np.int8
x = np.array([10,20,30,40], dtype = np.float32)
print("Data Type: ", x.dtype)
print(x)

Data Type:  float32
[10. 20. 30. 40.]


# What are Numpy Arithmetic Opereation

In [81]:
# a+b = np.add(a,b)
# (a-b) = np.subtract(a,b)
# (a*b) = np.multipy(a,b)
# (a/b) = np.divide(a,b)
# (a%b) = np.mod(a,b)
# (a**b) = np.power(a,b)
# 1/a = np.reciprocal(a,b)

In [82]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var + 3
print(varadd)

[4 5 6 7]


In [83]:
# add two array
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1+var2
print(varadd)

[2 4 6 8]


In [84]:
import numpy as np
var = np.array([1,2,3,4])
var1 = var/3
var1

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [87]:
# we can also use functions
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = np.add(var1, var2)
varadd

array([2, 4, 6, 8])

In [88]:
# 2d array
var1 = np.array([[1,2,3,4], [1,2,3,4]])
var2 = np.array([[3,4,5,6], [7,8,9,10]])
varadd = var1 + var2
varadd

array([[ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [89]:
# reciprocal function
var = np.array([1,2,3,4])
var_reci = np.reciprocal(var)
var_reci

array([1, 0, 0, 0])