In [1]:
                         # 1. INTRODUCTION TO NUMPY

# # List vs Array
# L = [1,2,3,4]
# print(L)
# [1, 2, 3, 4]  # comma separated output

# array output isn't comma separated
# Array = [1 2 3 4]

In [2]:
# Installation Numpy
# pip install numpy 
# Note: using pip command in cmd. It shows error in jupyter.

# Import Numpy
# Import numpy as np     # np is standard alias

In [3]:
# CREATING ARRAY IN NUMPY

import numpy as np
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
# CREATING LIST

y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [5]:
                        # 2. NUMPY ARRAYS vs. PYTHON LISTS
        
# numpy is faster than python list


In [6]:
# code to check run time
import numpy as np
%timeit [j**4 for j in range(1,9)]

2.22 µs ± 323 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [7]:
import numpy as np
%timeit np.arange(1,9)**4

5.56 µs ± 725 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
# The %timeit magic command in Jupyter Notebooks is used to 
# measure the execution time of a particular code snippet.

In [9]:
                        # 3. CREATION ARRAYS IN NUMPY
# 1.   
import numpy as np
x = [1,2,3,4]
y = np.array(x)
print(y)

[1 2 3 4]


In [10]:
# 2. aur bi simple kr skte hai upar wale code ko.
# we use this code 
import numpy as np
y = np.array([1,2,3,4])
print(y)

[1 2 3 4]


In [11]:
# 3. how to check it is array ?
# print ko hta do sirf y liko
# becaue print exact ans btata hai. not its data type
import numpy as np
y = np.array([1,2,3,4])
y

array([1, 2, 3, 4])

In [12]:
# 4. type (type se bi pta kr skte hai.)

import numpy as np
y = np.array([1,2,3,4])
print(type(y))

<class 'numpy.ndarray'>


In [13]:
# 5. creating array by user input
l = []
for i in range(1,5):
    int_1 = input("enter : ")
    l.append(int_1)
print(l)

enter : 12
enter : 13
enter : 14
enter : 15
['12', '13', '14', '15']


In [14]:
                      # DIMENSIONS IN ARRAY,  (USING 'ndim' functn)
# 1d array
# 2d array
# 3d array
# higher dimensional array (multidimensional array)

In [15]:
# 6. 1d array
import numpy as np
y = np.array([1,2,3,4])
print(y.ndim)

1


In [16]:
# 7. 2d array
arr2 = np.array([[1,2,3,4], [1,2,3,4]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [17]:
# 8. it shows error because data is heterogeneous (it iss 1d array)
arr2 = np.array([[1,2,3,4],[1,2,3]])
print(arr2)
print(arr2.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [18]:
# 9. 3d array
arr3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [19]:
# 10 multidimensional array (n dim means --> n dimensional)

arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [20]:
                    #4.CREATING ARRAY USING NUMPY FUNCTION
    
                # special numpy array
        
# zeros
import numpy as np
ar_zero = np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [21]:
# ones
import numpy as np
ar_ones = np.ones(4)
print(ar_ones)

[1. 1. 1. 1.]


In [22]:
# empty
import numpy as np
ar_empty = np.empty(4)
print(ar_empty)

# is empty me last program jo run kiya tha uska data aa jata hai.

[1. 1. 1. 1.]


In [23]:
# range
import numpy as np
ar_range = np.arange(4)
print(ar_range)
# range function - hme continuous order me array dega jitne range dalenge. using arange keyword

[0 1 2 3]


In [24]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [26]:
ar_lin = np.linspace(0,20, num = 5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


In [27]:
                        # 5. CREATE NUMPY ARRAYS WITH RANDOM NUMBERS
    
# RANDOM

# 1. rand()
# it gives no. (0 to 1) +ve

import numpy as np
var = np.random.rand(4)
print(var)

[0.78656772 0.15701851 0.41500292 0.81854303]


In [28]:
# 2. randn()  
# closer to 0 +ve,-ve

import numpy as np
var2 = np.random.randn(4)
print(var2)

[-0.83087565  1.5967742  -0.51735827  0.01181966]


In [29]:
# 3. randf()
# float (0.0 to 1.0)

var3 = np.random.ranf(4)
print(var3)

[0.08386031 0.13550512 0.13573885 0.06132518]


In [30]:
# 4 randint()
# min,max,data  (range me)
var4 = np.random.randint(5,20,4)
print(var4)

[14  9 13 16]


In [31]:
                        # 6. DATA TYPE IN NUMPY ARRAY


In [32]:
import numpy as np
var = np.array([1,2,3,4])
print("Data Type : ",var.dtype)

Data Type :  int32


In [33]:
import numpy as np
var = np.array([1,2,3,4,12,13,14,15])
print("Data Type : ",var.dtype)

Data Type :  int32


In [34]:
var = np.array(["A","S","D","F"])
print("Data Type : ",var.dtype)
# <U1 means output is string

Data Type :  <U1


In [35]:
# mixing of string + number
var = np.array(["A","S","D","F",1,2,3,4])
print("Data Type : ",var.dtype)
# U11 - STRING + NO.

Data Type :  <U11


In [36]:
                    # CONVERSION OF 1 DATA TYPE TO OTHER


In [37]:


x = np.array([1,2,3,4])
print("Data Type : ",x.dtype)

# now, we will convert its data type below.👇

Data Type :  int32


In [38]:
# case 1. np.int8

x = np.array([1,2,3,4], dtype = np.int8)
print("Data Type : ",x.dtype)
print(x)

Data Type :  int8
[1 2 3 4]


In [39]:
# code 1
x = np.array([1,2,3,4], dtype = np.float16)
print("Data Type : ",x.dtype)
print(x)

Data Type :  float16
[1. 2. 3. 4.]


In [40]:
#  case: 2 using short form
# code 2  

x = np.array([1,2,3,4], dtype = "f")
print("Data Type : ",x.dtype)
print(x)

# output
# Data Type :  float32
# [1. 2. 3. 4.]

Data Type :  float32
[1. 2. 3. 4.]


In [41]:
# see the difference in the code1 nd code2
# In the first code, you use np.float16.
# In the second code, you use "f", which is equivalent to np.float32.
    
# It seems that the second code has overridden the specified data type "f" with the default data type, which is float32. 
# If you want to use float16 in the second code, you should specify np.float16 explicitly:

In [42]:
# case 3 we can use this data type as a function.

x2 = np.array([1,2,3,4])
new = np.float32(x2)
new_one = np.int_(new)  # int_ underscore for int64 or int32
print("Data Type : ",x2.dtype)
print("Data Type : ",new.dtype)
print(new_one.dtype)

print(x2)
print(new)
print(new_one)

Data Type :  int32
Data Type :  float32
int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [43]:
# case 4 we can directly convert data type
# using as type function
x3 = np.array([1,2,3,4])
new_1 = x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


In [44]:
                    # 7. ARITHMETIC OPERATORS

In [45]:
# a+b   np.add(a,b)
# a-b   np.subtract(a,b)
# a*b   np.multiply(a,b)
# a/b   np.divide(a,b)
# a%b   np.mod(a,b)
# a**b  np.power(a,b)
# 1/a   np.reciprocal(a)

In [46]:
# we can use perform these arithmetic operations directly
# or we can use functions related to it.

In [47]:
# ARITHMETIC OPERATION

In [48]:
import numpy as np

var = np.array([1,2,3,4])
varadd = var + 3
print(varadd)

# every no. add by 3

[4 5 6 7]


In [49]:
# add two array
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 + var2

print(varadd)

[2 4 6 8]


In [50]:
import numpy as np

var = np.array([1,2,3,4])
varadd = var - 3
print(varadd)

[-2 -1  0  1]


In [51]:
import numpy as np

var = np.array([1,2,3,4])
varadd = var * 3
print(varadd)

[ 3  6  9 12]


In [52]:
import numpy as np

var = np.array([1,2,3,4])
varadd = var / 3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [53]:
import numpy as np

var = np.array([1,2,3,4])
varadd = var % 3  # modulus (remainder operator)
print(varadd)

[1 2 0 1]


In [54]:
# we can also use arithmetic ope as a funtion.

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = np.add(var1,var2)
print(varadd)

[2 4 6 8]


In [55]:
var1 = np.array([1,2,3,4])
varadd = np.add(var1,3)
print(varadd)
# sb 3 se add ho jayega

[4 5 6 7]


In [56]:
var = np.array([1,2,3,4])
varadd = np.reciprocal(var)
print(varadd)

[1 0 0 0]


In [57]:
# 2D array

In [58]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])
varadd = var21 + var22
print(varadd)

[[2 4 6 8]
 [2 4 6 8]]


In [59]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd = var21 + var22

print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [60]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd = var21 * var22

print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]


In [61]:
                        # 8. ARITHMETIC FUNCTIONS IN NUMPY ARRAY

In [62]:
# np.min(x)
# np.max(x)
# np.argmin(x) position,index
# np.sqrt(x)
# np.sin(x)
# np.cos(x)
# np.cumsum(x)

In [63]:
# min,max
import numpy as np
var = np.array([1,2,3,4,5,3,2])
print("min : ",np.min(var))
print("max : ",np.max(var))

min :  1
max :  5


In [64]:
# argmin,argmax
import numpy as np
var = np.array([1,2,3,4,5,3,2])
print("min : ",np.min(var),np.argmin(var))
print("max : ",np.max(var),np.argmax(var))

min :  1 0
max :  5 4


In [65]:
# axis

# along to row axis
import numpy as np
var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis=1))
# axis = 0 col
# axis = 1 row
# [2 1 3]
# [9 5 6]

[1 5]


In [66]:
# along to column axis
import numpy as np
var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis=0))

[2 1 3]


In [67]:
import numpy as np
var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis=0), np.argmin(var1))

[2 1 3] 1


In [82]:
# sqrt
import numpy as np
var = np.array([4,4,1,4,5,3,2])
print("sqrt : ",np.sqrt(var))
# note this is squre root not square.


sqrt :  [2.         2.         1.         2.         2.23606798 1.73205081
 1.41421356]


In [86]:
# sin(x), cos(x)
var2 = np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))   # note cumulative sum

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


In [2]:
                        #9. LEARN ABOUT SHAPE AND RESHAPING IN NUMPY ARRAYS

In [3]:
# SHAPE


In [5]:
import numpy as np
var = np.array([[1,2],[1,2]])
print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [6]:
import numpy as np
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [12]:
# MULTIDIMENSIONAL ARRAY
var1 = np.array([1,2,3,4], ndmin=4)
print(var1)
print()
print(var1.shape)  # 1,1,1 (3row) and 4 columns

[[[[1 2 3 4]]]]

(1, 1, 1, 4)


In [13]:
# RESHAPE

In [16]:
var2 = np.array([1,2,3,4,5,6])
x = var2.reshape(3,2)  # 3row and 2 element
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
var3 = np.array([1,2,3,4,5,6])
print(var3)
print(var3.ndim)
print()

x = var3.reshape(3,2)  #3row and 2 element

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [22]:
# var2 = np.array([1,2,3,4,5,6])
# x = var2.reshape(3,3)  # 3row and 3 element
# print(x)

# NOTE: V.imp reshape(3,3)
# isme 1st parameter means 3 rows
# and 2nd parameter means 3 elements in every row.
# but so it shows error bcoz hmara pass itne elment ni hai.

# and numpy ise null bi show ni kr skta.
# bcoz in numpy sare row elements se full hone chahiye.

ValueError: cannot reshape array of size 6 into shape (3,3)

In [24]:
var2 = np.array([1,2,3,4,5,6,1,2,3])
x = var2.reshape(3,3)  # 3row and 2 element
print(x)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [1]:
                        # 10 BROADCASTING (CAMPUSX YOUTUBE CHANNEL)

In [2]:
import numpy as np
# Scenario 1
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [3]:
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [4]:
# Scenario 2
a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)
print(a3,a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [5]:
a3 + a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [7]:
# BROADCASTING
# BROADCASTING IS THE ABILITY OF NUMPY TO PERFORM ARITHMETIC OPERATION ON DISSIMILAR ARRAYS.

In [8]:
# RULES OF BROADCASTING

a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [9]:
a5 = np.arange(3).reshape(1,3)
a6 = np.arange(12).reshape(4,3)
print(a5)
print(a6)
a5+a6

[[0 1 2]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [11]:
a7 = np.arange(4).reshape(4,1)
a8 = np.arange(12).reshape(4,3)
print(a7)
print(a8)
a7 + a8

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [12]:
a9 = np.arange(3).reshape(1,3)
a10 = np.arange(16).reshape(4,4)
print(a9)
print(a10)
a9 + a10
# it shows value error( becaues rules is not applicable)

[[0 1 2]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 

In [13]:
a11 = np.arange(3).reshape(1,3)
a12 = np.arange(3).reshape(3,1)
print(a11)
print(a12)
a11 + a12

[[0 1 2]]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [15]:
a13 = np.arange(1).reshape(1,1)
a14 = np.arange(20).reshape(4,5)
print(a13)
print(a14)
a13 + a14

[[0]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
a15 = np.arange(4)
a16 = np.arange(20).reshape(5,4)
print(a15)
print(a16)
a15 + a16

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])

In [1]:
                        # 10.BROADCASTING IN NUMPY ARRAYS

In [2]:
import numpy as np 
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3])
print(var1 + var2)
# show broadcasting error

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [3]:
import numpy as np 
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
print(var1 + var2)

[2 4 6 8]


In [9]:
import numpy as np
var1 = np.array([1,2,3])
print(var1.shape)
print()
print(var1)
print()


var2 = np.array([[1],[2],[3]])
print(var2)
print()
print(var2)

print(var1 + var2)


(3,)

[1 2 3]

[[1]
 [2]
 [3]]

[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [10]:
# broadcasting ke liye dono array me se kisi ke pass 1 hone chahiye
# and uske samne and corresponding wale same hone chahiye
# and dono ke right side right side compare krenge jo bda hoga wo order.
# example:
# (1,3) + (3,1) = (3,3)can add
# (1,3) + (1,4) can't add
# (1,3) + (1,3) = (3,3) add
# (2,1) + (2,1) can add
# (2,1) + (2,3) can add

In [13]:
# (2,1) + (2,1) can add
a = np.array([[1],[2]])
b = np.array([[3],[4]])
print(a)
print(a.shape)
print()
print(b)
print(b.shape)
print()
print(a+b)

[[1]
 [2]]
(2, 1)

[[3]
 [4]]
(2, 1)

[[4]
 [6]]


In [16]:
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)

print(x+y)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]
