In [1]:
# Numpy array is a multi dimensional data structure that is the core of scientific
# computing in python.
# it is homogeneous.
# automatic vectorization and broadcasting 
# provide efficient memory management. array has contigenous memory location.
# flexible, can indexing and slicing values.

# Dimensions in Array
# 0d --> scalar
# 1d --> vector
# 2d --> matrix
# 3d --> tensor

In [2]:
from array import *
arr = array('i', [1,2,3,4])
arr

array('i', [1, 2, 3, 4])

In [3]:
type(arr)

array.array

# numpy.arange() in Python

In [14]:

import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9,10])
print(var)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
var1 = np.arange(0,9,2) # start stop step
var1

array([0, 2, 4, 6, 8])

In [18]:
# indexing
var[2]

3

In [19]:
# slicing
var[2:5] # 5 is not include.

array([3, 4, 5])

In [67]:
# indexing in 2d array 
# import numpy as np
var5 = np.array([[1,2,3,4],[7,54,24,24]])
var5

array([[ 1,  2,  3,  4],
       [ 7, 54, 24, 24]])

In [70]:
var5[0,1]

2

In [69]:
var5[1,1]

54

In [71]:
# slicing
var5[0,::]

array([1, 2, 3, 4])

In [40]:
# view
arr = np.array([2,4,6,8,10])
v = arr.view()
print(id(arr))
print(id(v))
arr[0] = 12

2354476290800
2354475492976


In [41]:
print(arr)
print(v)

[12  4  6  8 10]
[12  4  6  8 10]


In [42]:
# copy of array in numpy
arr1 = np.array([2,4,6,8,10])
c = arr.copy()
print(id(arr1))
print(id(c))

2354475200944
2354475493168


In [38]:
arr1[0] = 12

In [39]:
print(arr1)
print(c)

[12  4  6  8 10]
[12  4  6  8 10]


In [43]:
# combine array in numpy

In [57]:
# concatenate
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
con = np.concatenate((arr1, arr2), axis = 0)
print(con)

[1 2 3 4 5 6 7 8]


In [59]:
stk = np.stack((arr1, arr2))
print(stk)

[[1 2 3 4]
 [5 6 7 8]]


In [60]:
stk = np.block((arr1, arr2))
print(stk)

TypeError: arrays is a tuple. Only lists can be used to arrange blocks, and np.block does not allow implicit conversion from tuple to ndarray.

# full form of numpy

In [ ]:
# NUMERICAL PYTHON.

# IPNYB FULL FORM. ==> INTERACTIVE PYTHON